auth:
  existingSecret: db-secret
  secretKeys:
    adminPasswordKey: password
    userPasswordKey: password
    usernameKey: username
    databaseKey: database

primary:
  persistence:
    enabled: true
    size: 5Gi
