apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: microservices
type: Opaque
data:
  postgresql-username: YWRtaW5fdXNlcg==    # 'admin_user'
  postgresql-password: cGFzc3dvcmQ=        # 'password'
  postgresql-database: ZGI=                # 'db'
