apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing-service
          image: bmanjunath1928/billing-service:1.0.0
          ports:
            - containerPort: 4001   # REST API
            - containerPort: 9001   # gRPC
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://billing-service-db-postgresql:5432/db
            - name: SPRING_DATASOURCE_USERNAME
              value: admin_user
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_SQL_INIT_MODE
              value: always
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: USER_SERVICE_ADDRESS
              value: user-service
            - name: USER_SERVICE_GRPC_PORT
              value: "9000"
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: microservices
spec:
  selector:
    app: billing-service
  ports:
    - name: http
      protocol: TCP
      port: 4001
      targetPort: 4001
    - name: grpc
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP
