apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workout-service
  template:
    metadata:
      labels:
        app: workout-service
    spec:
      containers:
        - name: workout-service
          image: bmanjunath1928/workout-service:latest
          ports:
            - containerPort: 4006   # REST API port
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://workout-service-db-postgresql:5432/db
            - name: SPRING_DATASOURCE_USERNAME
              value: admin_user
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_SQL_INIT_MODE
              value: always
---
apiVersion: v1
kind: Service
metadata:
  name: workout-service
  namespace: microservices
spec:
  selector:
    app: workout-service
  ports:
    - name: http
      protocol: TCP
      port: 4006
      targetPort: 4006
  type: ClusterIP
