version: "3.9"

networks:
  integration-tests_internal:
    name: integration-tests_internal

services:

  # =========================
  # Zookeeper & Kafka
  # =========================
  zookeeper:
    platform: linux/amd64
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - integration-tests_internal

  kafka:
    platform: linux/amd64
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - integration-tests_internal

  # =========================
  # Databases
  # =========================
  auth-db:
    platform: linux/amd64
    image: postgres:16
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - integration-tests_internal

  user-db:
    platform: linux/amd64
    image: postgres:16
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - integration-tests_internal

  nutrition-db:
    platform: linux/amd64
    image: postgres:16
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - integration-tests_internal

  notification-db:
    platform: linux/amd64
    image: postgres:16
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - integration-tests_internal

  workout-db:
    platform: linux/amd64
    image: postgres:16
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - integration-tests_internal

  billing-db:
    platform: linux/amd64
    image: postgres:16
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - integration-tests_internal

  # =========================
  # Core Services
  # =========================
  auth-service:
    platform: linux/amd64
    image: bmanjunath1928/auth-service:1.0.0
    depends_on:
      auth-db:
        condition: service_healthy
    ports:
      - "4005:4005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: lA93KpGHGfs92kSiD8JvUeF7lK7Jt4uQmQ4Q5u9pFvQ=
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4005/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
    networks:
      - integration-tests_internal

  billing-service:
    platform: linux/amd64
    image: bmanjunath1928/billing-service:1.0.0
    depends_on:
      billing-db:
        condition: service_healthy
    ports:
      - "4001:4001"
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://billing-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4001/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    networks:
      - integration-tests_internal

  user-service:
    platform: linux/amd64
    image: bmanjunath1928/user-service:1.0.0
    depends_on:
      user-db:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4000/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
    networks:
      - integration-tests_internal

  workout-service:
    platform: linux/amd64
    image: bmanjunath1928/workout-service:1.0.0
    depends_on:
      workout-db:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "4006:4006"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://workout-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_SQL_INIT_MODE: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4006/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
    networks:
      - integration-tests_internal

  nutrition-service:
    platform: linux/amd64
    image: bmanjunath1928/nutrition-service:1.0.0
    depends_on:
      nutrition-db:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "4009:4009"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://nutrition-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_SQL_INIT_MODE: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4009/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
    networks:
      - integration-tests_internal

  notification-service:
    platform: linux/amd64
    image: bmanjunath1928/notification-service:1.0.0
    depends_on:
      notification-db:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "4010:4010"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_SQL_INIT_MODE: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4010/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
    networks:
      - integration-tests_internal

  # =========================
  # API Gateway
  # =========================
  api-gateway:
    platform: linux/amd64
    image: bmanjunath1928/api-gateway:1.0.0
    ports:
      - "4004:4004"
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
      USER_SERVICE_URL: http://user-service:4000
      WORKOUT_SERVICE_URL: http://workout-service:4006
      NUTRITION_SERVICE_URL: http://nutrition-service:4009
      NOTIFICATION_SERVICE_URL: http://notification-service:4010
    entrypoint: [ "/wait-for-services.sh", "http://auth-service:4005", "http://user-service:4000", "http://workout-service:4006", "http://nutrition-service:4009", "http://notification-service:4010" ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4004/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
    networks:
      - integration-tests_internal
