version: "3.9"

services:
  # ------------------------
  # Databases
  # ------------------------
  auth-db:
    image: postgres:16
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password

  user-db:
    image: postgres:16
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password

  nutrition-db:
    image: postgres:16
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password

  notification-db:
    image: postgres:16
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password

  # ------------------------
  # Core Services
  # ------------------------
  auth-service:
    image: bmanjunath1928/auth-service:1.0.0
    ports:
      - "4005:4005"
    depends_on:
      - auth-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: test-secret

  user-service:
    image: bmanjunath1928/user-service:1.0.0
    ports:
      - "4000:4000"
    depends_on:
      - user-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password

  nutrition-service:
    image: bmanjunath1928/nutrition-service:1.0.0
    ports:
      - "4006:4006"
    depends_on:
      - nutrition-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://nutrition-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password

  notification-service:
    image: bmanjunath1928/notification-service:1.0.0
    ports:
      - "4007:4007"
    depends_on:
      - notification-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password

  # ------------------------
  # API Gateway
  # ------------------------
  api-gateway:
    image: bmanjunath1928/api-gateway:1.0.0
    ports:
      - "4004:4004"
    depends_on:
      - auth-service
      - user-service
      - nutrition-service
      - notification-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
      USER_SERVICE_URL: http://user-service:4000
      NUTRITION_SERVICE_URL: http://nutrition-service:4006
      NOTIFICATION_SERVICE_URL: http://notification-service:4007
