services:
  # =========================
  # Zookeeper & Kafka
  # =========================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "bash", "-c", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z kafka 9092"]
      interval: 10s
      timeout: 5s
      retries: 10

  # =========================
  # Databases
  # =========================
  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user"]
      interval: 5s
      timeout: 5s
      retries: 10

  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user"]
      interval: 5s
      timeout: 5s
      retries: 10

  nutrition-db:
    image: postgres:16
    container_name: nutrition-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user"]
      interval: 5s
      timeout: 5s
      retries: 10

  notification-db:
    image: postgres:16
    container_name: notification-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user"]
      interval: 5s
      timeout: 5s
      retries: 10

  workout-db:
    image: postgres:16
    container_name: workout-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user"]
      interval: 5s
      timeout: 5s
      retries: 10

  billing-db:
    image: postgres:16
    container_name: billing-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user"]
      interval: 5s
      timeout: 5s
      retries: 10

  # =========================
  # Core Services
  # =========================
  auth-service:
    image: bmanjunath1928/auth-service:1.0.0
    container_name: auth-service
    depends_on:
      auth-db:
        condition: service_healthy
    ports:
      - "4005:4005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: lA93KpGHGfs92kSiD8JvUeF7lK7Jt4uQmQ4Q5u9pFvQ=
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4005/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 15

  billing-service:
    image: bmanjunath1928/billing-service:1.0.0
    container_name: billing-service
    depends_on:
      billing-db:
        condition: service_healthy
    ports:
      - "4001:4001"
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://billing-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 15

  user-service:
    image: bmanjunath1928/user-service:1.0.0
    container_name: user-service
    depends_on:
      user-db:
        condition: service_healthy
      billing-service:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 15

  workout-service:
    image: bmanjunath1928/workout-service:1.0.0
    container_name: workout-service
    depends_on:
      workout-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "4006:4006"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://workout-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4006/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 15

  nutrition-service:
    image: bmanjunath1928/nutrition-service:1.0.0
    container_name: nutrition-service
    depends_on:
      nutrition-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "4009:4009"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://nutrition-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4009/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 15

  notification-service:
    image: bmanjunath1928/notification-service:1.0.0
    container_name: notification-service
    depends_on:
      notification-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "4010:4010"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4010/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 15

  # =========================
  # API Gateway
  # =========================
  api-gateway:
    image: bmanjunath1928/api-gateway:1.0.0
    container_name: api-gateway
    depends_on:
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      workout-service:
        condition: service_healthy
      nutrition-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    ports:
      - "4004:4004"
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4004/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 20
