name: Build & Push Docker Images

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
          docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # -------- api-gateway --------
      - name: Build & push api-gateway
        run: |
          docker build -t bmanjunath1928/api-gateway:${TAG} api-gateway
          docker push bmanjunath1928/api-gateway:${TAG}

      # -------- user-service --------
      - name: Build & push user-service
        run: |
          docker build -t bmanjunath1928/user-service:${TAG} user-service
          docker push bmanjunath1928/user-service:${TAG}

      # -------- auth-service --------
      - name: Build & push auth-service
        run: |
          docker build -t bmanjunath1928/auth-service:${TAG} auth-service
          docker push bmanjunath1928/auth-service:${TAG}

      # -------- billing-service --------
      - name: Build & push billing-service
        run: |
          docker build -t bmanjunath1928/billing-service:${TAG} billing-service
          docker push bmanjunath1928/billing-service:${TAG}

      # -------- notification-service --------
      - name: Build & push notification-service
        run: |
          docker build -t bmanjunath1928/notification-service:${TAG} notification-service
          docker push bmanjunath1928/notification-service:${TAG}

      # -------- nutrition-service --------
      - name: Build & push nutrition-service
        run: |
          docker build -t bmanjunath1928/nutrition-service:${TAG} nutrition-service
          docker push bmanjunath1928/nutrition-service:${TAG}

      # -------- workout-service --------
      - name: Build & push workout-service
        run: |
          docker build -t bmanjunath1928/workout-service:${TAG} workout-service
          docker push bmanjunath1928/workout-service:${TAG}

      # -------- analytics-service --------
      - name: Build & push analytics-service
        run: |
          docker build -t bmanjunath1928/analytics-service:${TAG} analytics-service
          docker push bmanjunath1928/analytics-service:${TAG}
