name: Build, Push & Deploy to Kubernetes (Minikube)

on:
  push:
    branches:
      - main

env:
  NAMESPACE: microservices
  TAG: ${{ github.sha }}

jobs:
  # =======================
  # CI: Build & Push Images
  # =======================
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
          docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & push api-gateway
        run: |
          docker build -t bmanjunath1928/prod-api-gateway:${TAG} api-gateway
          docker push bmanjunath1928/prod-api-gateway:${TAG}

      - name: Build & push user-service
        run: |
          docker build -t bmanjunath1928/prod-user-service:${TAG} user-service
          docker push bmanjunath1928/prod-user-service:${TAG}

      - name: Build & push auth-service
        run: |
          docker build -t bmanjunath1928/prod-auth-service:${TAG} auth-service
          docker push bmanjunath1928/prod-auth-service:${TAG}

      - name: Build & push billing-service
        run: |
          docker build -t bmanjunath1928/prod-billing-service:${TAG} billing-service
          docker push bmanjunath1928/prod-billing-service:${TAG}

      - name: Build & push notification-service
        run: |
          docker build -t bmanjunath1928/prod-notification-service:${TAG} notification-service
          docker push bmanjunath1928/prod-notification-service:${TAG}

      - name: Build & push nutrition-service
        run: |
          docker build -t bmanjunath1928/prod-nutrition-service:${TAG} nutrition-service
          docker push bmanjunath1928/prod-nutrition-service:${TAG}

      - name: Build & push workout-service
        run: |
          docker build -t bmanjunath1928/prod-workout-service:${TAG} workout-service
          docker push bmanjunath1928/prod-workout-service:${TAG}

      - name: Build & push analytics-service
        run: |
          docker build -t bmanjunath1928/prod-analytics-service:${TAG} analytics-service
          docker push bmanjunath1928/prod-analytics-service:${TAG}

      - name: Build & push ai-service
        run: |
          docker build -t bmanjunath1928/prod-ai-service:${TAG} ai-service
          docker push bmanjunath1928/prod-ai-service:${TAG}
      
