name: Deploy to Kubernetes (Minikube)

on:
  push:
    branches:
      - main

env:
  NAMESPACE: microservices
  TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Deploy microservices
        run: |
          kubectl set image deployment/api-gateway api-gateway=bmanjunath1928/prod-api-gateway:${TAG} -n $NAMESPACE
          kubectl set image deployment/auth-service auth-service=bmanjunath1928/prod-auth-service:${TAG} -n $NAMESPACE
          kubectl set image deployment/user-service user-service=bmanjunath1928/prod-user-service:${TAG} -n $NAMESPACE
          kubectl set image deployment/billing-service billing-service=bmanjunath1928/prod-billing-service:${TAG} -n $NAMESPACE
          kubectl set image deployment/notification-service notification-service=bmanjunath1928/prod-notification-service:${TAG} -n $NAMESPACE
          kubectl set image deployment/nutrition-service nutrition-service=bmanjunath1928/prod-nutrition-service:${TAG} -n $NAMESPACE
          kubectl set image deployment/workout-service workout-service=bmanjunath1928/prod-workout-service:${TAG} -n $NAMESPACE
          kubectl set image deployment/analytics-service analytics-service=bmanjunath1928/prod-analytics-service:${TAG} -n $NAMESPACE

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/api-gateway -n $NAMESPACE
          kubectl rollout status deployment/user-service -n $NAMESPACE
